### ISSUE TITLE
URL in clipboard is always the same and is not correct

### ISSUE THREAD

**Issue by vdesabou** [alexreg/Cloudup-Alfred-Workflow#1]
Hi,

Whatever the file I try to share, I get in clipboard at the end this URL https://cloudup.com/cwKeQpvom03 which is incorrect one. However the file is correctly uploaded.

Any idea why?
Thanks

**Comment by SpaceK33z** [comment]
Hm, that's weird. I'm trying to reproduce the problem, but for me it's working perfectly. It's especially weird because I'm using [the official node package](https://npmjs.org/package/cloudup) (built by Cloudup) to handle the copy/paste part. 

Is the URL also incorrect when you hold cmd (so that it opens in the browser)?

Also, I've made some changes to the workflow, can you try if this works? [Download here](https://github.com/SpaceK33z/Cloudup-Alfred-Workflow/blob/master/Cloudup.alfredworkflow?raw=true)

**Comment by vdesabou** [comment]
Hi,

I can't reproduce with last version. Strange..
In any case that's a wonderful workflow, thanks for sharing this.
